config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  concern :pagingable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users
  resources :credentials, concerns: :pagingable do
    get :edit_document, on: :member
  end
  root to: 'credentials#index'
end

app/models/credential.rb
class Credential < ApplicationRecord
  include Filterable

  # ownership of the credential
  belongs_to :access_group, optional: true

  # virtual attribute for the secured document
  attribute :document, :text
  # virtual attribute for the optional document password
  attribute :password

  # Callbacks
  before_validation :normalize_title
  before_create :set_token
  after_save :save_document
  after_destroy :reset_document

  # Validations
  validates :title,
    presence: true,
    uniqueness: { case_sensitive: false }

  # validates :token,
    # presence: true,
    # uniqueness: true

  validates :password,
    presence: true,
    if: -> { self.secured }

  validate :document_successfully_decrypted,
    if: -> { self.secured && self[:document].present? }

  scope :ordered, -> { order :title }
  scope :title_filter, -> (title) { where('lower(title) like ?', "%#{title.downcase.strip}%") }
  scope :url_filter, -> (url) { where('lower(url) like ?', "%#{url.downcase.strip}%") }
  scope :access_groups, -> (*access_groups) { where('access_group_id in (?)', *access_groups) }

  def document
    self[:document] = HVDigitalSafe::SecureDataStorage.new(self.token).document
    if self.secured
      self[:document] = HVCrypto::Synchron.new(self.password).decode(self[:document])
    end
    self[:document]
  end

  def document=(doc)
    if self.secured
      # self[:document] = HVCrypto::Synchron.new(self.password).encode(doc)
      super(HVCrypto::Synchron.new(self.password).encode(doc))
    else
      # self[:document] = doc
      super(doc)
    end
  end

  private
    def normalize_title
      self.title.strip! if self.title.present?
    end

    def set_token
      max_retries = 10
      retries = 0
    
      loop do
        self.token = HVDigitalSafe::SecureDataStorage.new.token
        break unless Credential.exists?(token: self.token)
    
        retries += 1
        if retries >= max_retries
          errors.add(:token, "could not generate a unique token after #{max_retries} attempts")
          raise ActiveRecord::RecordInvalid.new(self)
        end
      end
    end

    def save_document
      doc = self[:document]
      doc.blank? || HVDigitalSafe::SecureDataStorage.new(self.token, doc).save
    end

    def reset_document
      doc = Faker::Internet.password(min_length: 8, max_length: 20, mix_case: true, special_characters: true)
      HVDigitalSafe::SecureDataStorage.new(self.token, doc).save
    end

    def document_successfully_decrypted
      if self[:document] == HVCrypto::Synchron::WRONG_PASSWORD
        errors.add(:password, :invalid)
        errors.add(:document, :invalid)
      end
   end
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_action :set_credential, only: [:show, :edit, :edit_document, :update, :destroy]

  # GET /credentials
  def index
    @credentials = Credential.access_groups(access_group_ids).
                              filter_by(filter_params).
                              ordered.
                              page(params[:page])
  end

  # GET /credentials/1
  def show
    render :edit
  end

  # GET /credentials/new
  def new
    @credential = Credential.new(access_group: default_access_group)
  end

  # GET /credentials/1/edit_document
  def edit_document
    # FIXME:  don't expose the token to the public
    # @credential.token = nil
    # password is set in the update method
    @credential.password = session[:password]
    session[:password] = nil
    if !@credential.secured || (@credential.secured && !@credential.password.blank?)
      @credential.document
    end
    render :edit, status: @credential.valid? ? :ok : :forbidden
  end

  # GET /credentials/1/edit
  def edit
    # FIXME: don't expose the token to the public
    # @credential.token = nil
  end

  # POST /credentials
  def create
    @credential = Credential.new(credential_params)

    if @credential.save
      redirect_to @credential, notice: t('.notice', default: 'Credential was successfully created.')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /credentials/1
  def update
    unless params[:decrypt].blank?
      session[:password] = params[:credential][:password]
      redirect_to edit_document_credential_path(@credential)
    else
      if @credential.update(credential_params)
        redirect_to @credential, notice: t('.notice', default: 'Credential was successfully updated.')
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /credentials/1
  def destroy
    @credential.destroy
    redirect_to credentials_url, notice: t('.notice', default: 'Credential was successfully destroyed.')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credential
      @credential = Credential.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def credential_params
      params.require(:credential).permit(:title, :url, :login, :comment, :secured, :password, :document, :access_group_id)
    end
    def filter_params
      params.slice(:title_filter, :url_filter)
    end

    def access_group_ids
      current_user.access_groups.map { |g| g.id }
    end
    def default_access_group
      current_user.default_access_group
    end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_form.html.haml
-#= debug assigns.inspect
= simple_form_for(@credential, wrapper: :floating_labels_form, html: { autocomplete: :off }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    %div{ data: { controller: 'url-opener' }, class: 'position-relative' }
      = f.input :url,
        input_html: { data: { 'url-opener-target': 'input' } }
      %a{ href: '#',
      target: '_blank',
      class: 'd-none btn btn-sm btn-outline-none position-absolute top-0 end-0 me-4 mt-3',
      data: { 'url-opener-target': 'link' }
      }
        %i.bi.bi-box-arrow-up-right{ aria: { hidden: 'true' } }
    %div{ data: { controller: 'clipboard', 'clipboard-success-content-value': t('.copied', default: 'Copied') }, class: 'position-relative' }
      = f.input :login,
        input_html: { data: { 'clipboard-target': 'source' } }
      = button_tag type: 'button',
        data: { action: 'clipboard#copy', 'clipboard-target': 'button' },
        class: 'btn btn-sm btn-outline-none position-absolute top-0 end-0 me-4 mt-3' do
        %i.bi.bi-clipboard{ 'aria-hidden': true }
        %span.visually-hidden= t('.copy', default: 'Copy to clipboard')
    -unless @credential.new_record?
      %div{ data: { controller: 'reveal', 'reveal-hidden-class': 'd-none' } }
        = f.input :secured, input_html: { data: { action: 'click->reveal#toggle' } }
        = f.input :password,
          required: true,
          input_html: { autocomplete: "section-#{ENV['USER']}-kg-#{dom_id(@credential)} current-password" },
          wrapper_html: { data: { 'reveal-target': 'item' }, class: @credential.secured ? '' : 'd-none' }
        -if @credential.secured && @credential.password.blank?
          = f.input :document, disabled: true
        -else
          %div{ data: { controller: 'clipboard', 'clipboard-success-content-value': t('.copied', default: 'Copied') }, class: 'position-relative' }
            = f.input :document,
              input_html: { data: { controller: 'textarea-autogrow', 'clipboard-target': 'source' } }
            = button_tag type: 'button',
              data: { action: 'clipboard#copy', 'clipboard-target': 'button' },
              class: 'btn btn-sm btn-outline-none position-absolute top-0 end-0 me-4 mt-1' do
              %i.bi.bi-clipboard{ 'aria-hidden': true }
              %span.visually-hidden= t('.copy', default: 'Copy to clipboard')
    = f.input :comment, input_html: { data: { controller: 'textarea-autogrow' } }
    -if current_user.access_groups.count > 1
      = f.association :access_group, collection: current_user.access_groups, include_blank: false, as: :radio_buttons, wrapper: :horizontal_collection_inline
    -else
      = f.hidden_field :access_group_id

  .form-actions
    -if !@credential.new_record? && @credential.secured
      = button_tag type: :submit, name: :decrypt, value: t('.actions.decrypt', default: 'Decrypt Password'), class: 'btn btn-outline-primary float-start' do
        %i.bi.bi-unlock{ 'aria-hidden': true }
        = t('.actions.decrypt', default: 'Decrypt Password')
    .inline-flex.float-end
      = f.button :button, t('.reset', default: 'Reset'), class: 'btn btn-outline-warning', type: :reset, as: :button
      = link_to t('.cancel', default: 'Cancel'), credentials_path, class: 'btn btn-outline-secondary', type: :button
      = button_tag type: :submit, class: 'btn btn-primary' do
        -# %i.bi.bi-save2{ 'aria-hidden': true }
        %i.bi.bi-floppy{ 'aria-hidden': true }
        = t('.actions.submit', default: 'Update Credential')

app/views/credentials/edit.html.haml
%h1
  = t('.header', default: 'Editing credential')
  %smaller.float-end
    = link_to new_credential_path, class: 'btn btn-outline-primary', type: :button do
      %i.bi.bi-journal-plus{ 'aria-hidden': true }
      = t('.actions.new', default: 'New Credential')

= render 'form'

app/views/credentials/index.html.haml
.page-header
  %h1
    = t('.header', default: 'Credentials')
    %smaller.float-end
      = link_to new_credential_path, class: 'btn btn-outline-primary', type: :button do
        %i.bi.bi-journal-plus{ 'aria-hidden': true }
        = t('.actions.new', default: 'New Credential')

  .filter.row.g-3.align-items-center
    .col-auto
      = simple_form_for '', wrapper: :floating_labels_form, method: :get, html: { role: 'search' } do |f|
        .row.g-3.align-items-center
          .col-auto
            = f.input :title_filter, label: t('.filter.title', default: 'Title'), required: false, input_html: { value: params[:title_filter] }
          .col-auto
            .text-center.mb-3
              #{ t('.filter.or', default: 'or') }
          .col-auto
            = f.input :url_filter, label: t('.filter.url', default: 'URL'), as: :string, required: false, input_html: { value: params[:url_filter] }
          .col-auto.mb-3
            = f.button :submit, t('.filter.search', default: 'Search'), class: 'btn-primary mt-0'
          .col-auto.mb-3
            = link_to t('.filter.reset', default: 'Reset'), request.path, class: 'btn btn-outline-warning', data: { "bs-toggle": 'tooltip', "bs-placement": 'top', "bs-title": t('.filter.clear_tooltip', default: 'Clear all search fields and update the results.') }

    .col-auto.ms-auto
      .paging.g-3.align-items-center
        = paginate @credentials

%section.section
  .container-fluid
    .row.justify-content-center
      .col-12
        .card-scroll-container{ data: { controller: "scroll-height", "scroll-height": { target: "scrollContainer", "elements-classes-value": '[".main-header", ".page-header", ".messages"]' } } }
          .row.row-cols-1.row-cols-md-2.row-cols-lg-3.g-2
            - @credentials.each do |credential|
              .col
                .card.shadow-sm.h-100
                  .card-header.d-flex.justify-content-between.align-items-center
                    .d-flex.flex-column
                      - if credential.url.present? && credential.url.start_with?("http://", "https://")
                        %a.card-title.h5.mb-0{ href: credential.url, target: "_blank" }= credential.title
                      - else
                        %h5.card-title.m-0= credential.title
                        - if credential.url.present?
                          .card-subtitle.mb-2= truncate(credential.url, length: 30, separator: '/')
                    %div.btn-group
                      = link_to edit_credential_path(credential), class: 'btn btn-outline-primary btn-sm' do
                        %i.bi.bi-pencil{ 'aria-hidden': true }
                      = link_to credential, data: { turbo_method: :delete, turbo_confirm: t('.actions.confirm', default: 'Are you sure?') }, class: 'btn btn-outline-danger btn-sm', method: :delete do
                        %i.bi.bi-trash3{ 'aria-hidden': true }
                  .card-body
                    %p.card-text
                      %div{data: { controller: 'clipboard', 'clipboard-success-content-value': t('.copied', default: 'Copied') }, class: 'position-relative' }
                        %strong= t('.login', default: 'Login') 
                        %span{ data: { 'clipboard-target': 'source' } }= credential.login
                        = button_tag type: 'button',
                          data: { action: 'clipboard#copy', 'clipboard-target': 'button' },
                          class: 'btn btn-sm btn-outline-none position-absolute top-0' do
                          %i.bi.bi-clipboard{ 'aria-hidden': true }
                          %span.visually-hidden= t('.copy', default: 'Copy to clipboard')
                    - unless credential.secured
                      %p.card-text
                        %div{data: { controller: 'clipboard', 'clipboard-success-content-value': t('.copied', default: 'Copied') }, class: 'position-relative' }
                          %strong= t('.document', default: 'Password') 
                          = button_tag type: 'button',
                            data: { action: 'clipboard#copy', 'clipboard-target': 'button' },
                            class: 'btn btn-sm btn-outline-none position-absolute top-0' do
                            %i.bi.bi-clipboard{ 'aria-hidden': true }
                            %span.visually-hidden= t('.copy', default: 'Copy to clipboard')
                          %div.mt-3{ data: { 'clipboard-target': 'source' } }= credential.document
                    - else
                      %p.card-text
                        %strong= t('.document', default: 'Password') 
                        = HVCrypto::Synchron::WRONG_PASSWORD
                    - if credential.comment.present?
                      %p.card-text
                        %strong= t('.comment', default: 'Comment') 
                        = simple_format(credential.comment)

app/views/credentials/new.html.haml
%h1= t('.header', default: 'New credential')

= render 'form'